
"""
AI/ML agents for Business Rescue OS.

Four Groq-powered agents:
1. Sales Agent
2. Inventory Agent
3. Finance Agent
4. Strategy Agent

Web Research Agent:
- Uses DuckDuckGo through the free ddgs package.
- Can optionally use Tavily if TAVILY_API_KEY is available.

Every Groq response is parsed as JSON.
Every agent has a safe fallback so one failed call
does not crash the complete demo pipeline.

run_pipeline(problem_id) is the single public function
the backend should call.
"""

import os
import sys
import json
from dotenv import load_dotenv

load_dotenv()

if sys.platform == "win32":
    try:
        sys.stdout.reconfigure(encoding="utf-8")
    except Exception:
        pass

from database.db import SessionLocal
from database.models import Problem, Product
from ai_ml.web_research_agent import search_external_options


# --------------------------------------------------------------------------
# Configuration
# --------------------------------------------------------------------------

GROQ_MODEL = os.environ.get("GROQ_MODEL", "openai/gpt-oss-120b")


_client = None


# --------------------------------------------------------------------------
# Groq Client
# --------------------------------------------------------------------------

def get_client():
    """
    Create and cache the Groq client.
    """

    global _client

    if _client is None:

        api_key = os.environ.get("GROQ_API_KEY")

        if not api_key:
            raise RuntimeError(
                "GROQ_API_KEY environment variable is not set."
            )

        from groq import Groq

        _client = Groq(
            api_key=api_key
        )

    return _client


# --------------------------------------------------------------------------
# Groq JSON Helper
# --------------------------------------------------------------------------

def _call_groq_json(system_prompt: str, user_content: str) -> dict:
    """
    Call Groq and return a parsed JSON dictionary.
    """

    client = get_client()

    response = client.chat.completions.create(
        model=GROQ_MODEL,
        messages=[
            {
                "role": "system",
                "content": system_prompt
            },
            {
                "role": "user",
                "content": user_content
            }
        ],
        temperature=0.2,
        response_format={
            "type": "json_object"
        }
    )

    content = response.choices[0].message.content

    result = json.loads(content)

    if not isinstance(result, dict):
        raise ValueError(
            "Groq response was not a JSON object."
        )

    return result


# --------------------------------------------------------------------------
# Sales Agent
# --------------------------------------------------------------------------

def sales_agent(problem_data: dict) -> dict:
    """
    Estimate realistic demand/sell-through for the units at risk.
    """

    system_prompt = """
You are the Sales Agent.

Single responsibility:
Estimate realistic sell-through for the units at risk based only on the
provided business problem.

Use the exact units_at_risk and value_at_risk from the database.
Do not invent or modify those numbers.

All financial amounts are in INR (Indian Rupees).

estimated_units_sold must not exceed units_at_risk.

Return ONLY valid JSON matching this schema:

{
  "sell_through_estimate_pct": "number",
  "estimated_units_sold": "number",
  "sales_reason": "string"
}
"""

    user_content = json.dumps(
        problem_data
    )

    try:

        result = _call_groq_json(
            system_prompt,
            user_content
        )

        # Basic safety checks on the LLM response.
        units_at_risk = int(
            problem_data["units_at_risk"]
        )

        sell_through = float(
            result.get(
                "sell_through_estimate_pct",
                0
            )
        )

        estimated_units = int(
            result.get(
                "estimated_units_sold",
                0
            )
        )

        sell_through = max(
            0,
            min(100, sell_through)
        )

        estimated_units = max(
            0,
            min(units_at_risk, estimated_units)
        )

        result["sell_through_estimate_pct"] = sell_through
        result["estimated_units_sold"] = estimated_units
        result["sales_reason"] = str(
            result.get(
                "sales_reason",
                "Sales assessment generated by the Sales Agent."
            )
        )

        return result

    except Exception as e:

        print(
            f"[Sales Agent] Groq failed. Using fallback: {e}"
        )

        units = int(
            problem_data["units_at_risk"]
        )

        estimated_units = round(
            units * 0.40
        )

        return {
            "sell_through_estimate_pct": 40,
            "estimated_units_sold": estimated_units,
            "sales_reason": (
                "Fallback estimate because the Sales Agent "
                "was unavailable."
            )
        }


# --------------------------------------------------------------------------
# Inventory Agent
# --------------------------------------------------------------------------

def inventory_agent(problem_data: dict) -> dict:
    """
    Assess stock distribution and identify whether transfer is a candidate.
    """

    system_prompt = """
You are the Inventory Agent.

Single responsibility:
Assess how the at-risk stock should be distributed across branches and
flag whether transferring stock to a higher-demand branch is a candidate.

Use only the provided data.

Use the exact units_at_risk and value_at_risk from the database.
Do not invent or modify those numbers.

If branch-level data is not provided, clearly state that branch information
is unavailable. Do not invent a specific branch name.

Return ONLY valid JSON matching this schema:

{
  "inventory_issue": "string",
  "transfer_recommended": "boolean",
  "transfer_candidate": "string",
  "inventory_notes": "string"
}
"""

    user_content = json.dumps(
        problem_data
    )

    try:

        result = _call_groq_json(
            system_prompt,
            user_content
        )

        transfer_recommended = result.get(
            "transfer_recommended",
            False
        )

        if not isinstance(
            transfer_recommended,
            bool
        ):
            transfer_recommended = False

        result["inventory_issue"] = str(
            result.get(
                "inventory_issue",
                "Inventory assessment generated by the Inventory Agent."
            )
        )

        result["transfer_recommended"] = (
            transfer_recommended
        )

        result["transfer_candidate"] = str(
            result.get(
                "transfer_candidate",
                ""
            )
        )

        result["inventory_notes"] = str(
            result.get(
                "inventory_notes",
                ""
            )
        )

        return result

    except Exception as e:

        print(
            f"[Inventory Agent] Groq failed. Using fallback: {e}"
        )

        return {
            "inventory_issue": (
                "Excess inventory requires redistribution."
            ),
            "transfer_recommended": False,
            "transfer_candidate": (
                "Branch data unavailable"
            ),
            "inventory_notes": (
                "Fallback assessment because the Inventory Agent "
                "was unavailable."
            )
        }


# --------------------------------------------------------------------------
# Finance Agent
# --------------------------------------------------------------------------

def finance_agent(
    problem_data: dict,
    sales_result: dict,
    inventory_result: dict
) -> dict:
    """
    Convert sales and inventory assessments into financial risk
    and expected-value numbers.
    """

    system_prompt = """
You are the Finance Agent.

Single responsibility:
Turn the business problem, sales assessment, and inventory assessment into
financial risk and expected-value estimates.

Use the exact units_at_risk and value_at_risk from the database.
Do not change those values.

All financial amounts are in INR (Indian Rupees).

Use the Sales Agent's estimated_units_sold as an important input when
estimating expected recovery.

The expected_recovery must be a number no greater than value_at_risk.

The remaining_risk must equal:

value_at_risk - expected_recovery

Return ONLY valid JSON matching this schema:

{
  "risk_level": "string",
  "expected_recovery": "number",
  "remaining_risk": "number",
  "finance_notes": "string"
}
"""

    user_content = json.dumps({
        "problem": problem_data,
        "sales_assessment": sales_result,
        "inventory_assessment": inventory_result
    })

    try:

        result = _call_groq_json(
            system_prompt,
            user_content
        )

        value_at_risk = float(
            problem_data["value_at_risk"]
        )

        expected_recovery = float(
            result.get(
                "expected_recovery",
                0
            )
        )

        expected_recovery = max(
            0,
            min(value_at_risk, expected_recovery)
        )

        remaining_risk = round(
            value_at_risk - expected_recovery,
            2
        )

        result["risk_level"] = str(
            result.get(
                "risk_level",
                "High"
            )
        )

        result["expected_recovery"] = round(
            expected_recovery,
            2
        )

        result["remaining_risk"] = remaining_risk

        result["finance_notes"] = str(
            result.get(
                "finance_notes",
                ""
            )
        )

        return result

    except Exception as e:

        print(
            f"[Finance Agent] Groq failed. Using fallback: {e}"
        )

        value_at_risk = float(
            problem_data["value_at_risk"]
        )

        sell_through_pct = sales_result.get(
            "sell_through_estimate_pct",
            40
        )

        try:
            sell_through_pct = float(
                sell_through_pct
            )
        except (
            TypeError,
            ValueError
        ):
            sell_through_pct = 40

        sell_through_pct = max(
            0,
            min(100, sell_through_pct)
        )

        expected_recovery = round(
            value_at_risk * (
                sell_through_pct / 100
            ),
            2
        )

        remaining_risk = round(
            value_at_risk - expected_recovery,
            2
        )

        return {
            "risk_level": "High",
            "expected_recovery": expected_recovery,
            "remaining_risk": remaining_risk,
            "finance_notes": (
                "Fallback financial estimate based on the Sales Agent "
                "sell-through estimate because the Finance Agent "
                "was unavailable."
            )
        }


# --------------------------------------------------------------------------
# Strategy Agent
# --------------------------------------------------------------------------

def strategy_agent(
    problem_data: dict,
    sales_result: dict,
    inventory_result: dict,
    finance_result: dict,
    external_options: list
) -> dict:
    """
    Compare all available information and produce the recovery strategy.
    """

    system_prompt = """
You are the Strategy Agent.

Single responsibility:
Compare the Sales, Inventory, Finance, and Web Research results and create
the best practical recovery strategy.

Use the exact units_at_risk and value_at_risk from the database.
Do not invent or modify those numbers.

Use the Finance Agent's expected_recovery as the recovery target.
Do not create a different expected_recovery.

The total action units must not exceed units_at_risk.

The recovery_plan expected_recovery must equal the Finance Agent's
expected_recovery.

The remaining_risk must equal:

value_at_risk - expected_recovery

All financial amounts are in INR (Indian Rupees).

Actions should be practical and directly related to the available
Sales, Inventory, Finance, and Web Research results.

If transfer is not recommended by the Inventory Agent, do not create
a transfer action.

Return ONLY valid JSON matching this schema:

{
  "recommended_option": "string",
  "reason": "string",
  "recovery_plan": {
    "expected_recovery": "number",
    "actions": [
      {
        "units": "number",
        "action": "string"
      }
    ],
    "remaining_risk": "number"
  }
}
"""

    user_content = json.dumps({
        "problem": problem_data,
        "sales_assessment": sales_result,
        "inventory_assessment": inventory_result,
        "finance_assessment": finance_result,
        "external_options": external_options
    })

    try:

        result = _call_groq_json(
            system_prompt,
            user_content
        )

        # --------------------------------------------------------------
        # Validate Strategy Agent output
        # --------------------------------------------------------------

        recovery_plan = result.get(
            "recovery_plan"
        )

        if not isinstance(
            recovery_plan,
            dict
        ):
            raise ValueError(
                "Strategy Agent returned an invalid recovery_plan."
            )

        finance_recovery = float(
            finance_result.get(
                "expected_recovery",
                0
            )
        )

        value_at_risk = float(
            problem_data["value_at_risk"]
        )

        units_at_risk = int(
            problem_data["units_at_risk"]
        )

        # Force Strategy to stay consistent with Finance.
        recovery_plan["expected_recovery"] = round(
            min(
                finance_recovery,
                value_at_risk
            ),
            2
        )

        recovery_plan["remaining_risk"] = round(
            value_at_risk
            - recovery_plan["expected_recovery"],
            2
        )

        # --------------------------------------------------------------
        # Validate and clean actions
        # --------------------------------------------------------------

        raw_actions = recovery_plan.get(
            "actions",
            []
        )

        if not isinstance(
            raw_actions,
            list
        ):
            raw_actions = []

        clean_actions = []
        total_units = 0

        for action in raw_actions:

            if not isinstance(
                action,
                dict
            ):
                continue

            try:

                action_units = int(
                    action.get(
                        "units",
                        0
                    )
                )

            except (
                TypeError,
                ValueError
            ):
                continue

            if action_units <= 0:
                continue

            remaining_units = (
                units_at_risk - total_units
            )

            if remaining_units <= 0:
                break

            action_units = min(
                action_units,
                remaining_units
            )

            clean_actions.append({
                "units": action_units,
                "action": str(
                    action.get(
                        "action",
                        "Recovery action"
                    )
                )
            })

            total_units += action_units

        recovery_plan["actions"] = clean_actions

        result["recommended_option"] = str(
            result.get(
                "recommended_option",
                "Manual review needed"
            )
        )

        result["reason"] = str(
            result.get(
                "reason",
                "Strategy generated from available agent assessments."
            )
        )

        result["recovery_plan"] = recovery_plan

        return result

    except Exception as e:

        print(
            f"[Strategy Agent] Groq failed. Using fallback: {e}"
        )

        units = int(
            problem_data["units_at_risk"]
        )

        value = float(
            problem_data["value_at_risk"]
        )

        # Use Finance Agent's number instead of inventing a new one.
        try:

            expected_recovery = float(
                finance_result.get(
                    "expected_recovery",
                    0
                )
            )

        except (
            TypeError,
            ValueError
        ):

            expected_recovery = 0

        expected_recovery = min(
            max(0, expected_recovery),
            value
        )

        remaining_risk = round(
            value - expected_recovery,
            2
        )

        # Only recommend transfer if Inventory Agent recommends it.
        if inventory_result.get(
            "transfer_recommended",
            False
        ):

            transfer_units = units // 2
            external_units = units - transfer_units

            actions = [
                {
                    "units": transfer_units,
                    "action": (
                        "Transfer to a higher-demand branch"
                    )
                },
                {
                    "units": external_units,
                    "action": (
                        "Explore external distributor "
                        "or liquidation"
                    )
                }
            ]

            recommended_option = (
                "Combined transfer and external recovery"
            )

        else:

            actions = [
                {
                    "units": units,
                    "action": (
                        "Use direct sales promotion "
                        "and external recovery"
                    )
                }
            ]

            recommended_option = (
                "Direct sales and external recovery"
            )

        return {
            "recommended_option": recommended_option,
            "reason": (
                "Fallback recovery strategy because the "
                "Strategy Agent was unavailable."
            ),
            "recovery_plan": {
                "expected_recovery": round(
                    expected_recovery,
                    2
                ),
                "actions": actions,
                "remaining_risk": remaining_risk
            }
        }


# --------------------------------------------------------------------------
# Final JSON Contract Validation
# --------------------------------------------------------------------------

def _validate_final_report(report: dict) -> bool:
    """
    Lightweight validation of the final JSON contract.

    This runs immediately before run_pipeline() returns the result,
    preventing malformed data from reaching the backend/dashboard.
    """

    if not isinstance(
        report,
        dict
    ):
        raise ValueError(
            "Final report must be a JSON object."
        )

    # --------------------------------------------------------------
    # Required top-level fields
    # --------------------------------------------------------------

    required_sections = [
        "problem",
        "sales_assessment",
        "inventory_assessment",
        "finance_assessment",
        "external_options",
        "recommended_option",
        "recovery_plan"
    ]

    for section in required_sections:

        if section not in report:

            raise ValueError(
                f"Final report is missing required field: {section}"
            )

    # --------------------------------------------------------------
    # Validate problem
    # --------------------------------------------------------------

    problem = report["problem"]

    if not isinstance(
        problem,
        dict
    ):
        raise ValueError(
            "problem must be an object."
        )

    for field in [
        "product",
        "units_at_risk",
        "value_at_risk",
        "root_cause"
    ]:

        if field not in problem:

            raise ValueError(
                f"problem is missing required field: {field}"
            )

    # --------------------------------------------------------------
    # Validate Sales Assessment
    # --------------------------------------------------------------

    sales = report["sales_assessment"]

    if not isinstance(
        sales,
        dict
    ):
        raise ValueError(
            "sales_assessment must be an object."
        )

    for field in [
        "sell_through_estimate_pct",
        "estimated_units_sold",
        "sales_reason"
    ]:

        if field not in sales:

            raise ValueError(
                f"sales_assessment is missing field: {field}"
            )

    # --------------------------------------------------------------
    # Validate Inventory Assessment
    # --------------------------------------------------------------

    inventory = report["inventory_assessment"]

    if not isinstance(
        inventory,
        dict
    ):
        raise ValueError(
            "inventory_assessment must be an object."
        )

    for field in [
        "inventory_issue",
        "transfer_recommended",
        "transfer_candidate",
        "inventory_notes"
    ]:

        if field not in inventory:

            raise ValueError(
                f"inventory_assessment is missing field: {field}"
            )

    if not isinstance(
        inventory["transfer_recommended"],
        bool
    ):
        raise ValueError(
            "transfer_recommended must be boolean."
        )

    # --------------------------------------------------------------
    # Validate Finance Assessment
    # --------------------------------------------------------------

    finance = report["finance_assessment"]

    if not isinstance(
        finance,
        dict
    ):
        raise ValueError(
            "finance_assessment must be an object."
        )

    for field in [
        "risk_level",
        "expected_recovery",
        "remaining_risk",
        "finance_notes"
    ]:

        if field not in finance:

            raise ValueError(
                f"finance_assessment is missing field: {field}"
            )

    # --------------------------------------------------------------
    # Validate External Options
    # --------------------------------------------------------------

    external_options = report[
        "external_options"
    ]

    if not isinstance(
        external_options,
        list
    ):
        raise ValueError(
            "external_options must be a list."
        )

    for option in external_options:

        if not isinstance(
            option,
            dict
        ):
            raise ValueError(
                "Each external option must be an object."
            )

        for field in [
            "name",
            "reason",
            "source_url"
        ]:

            if field not in option:

                raise ValueError(
                    f"External option is missing field: {field}"
                )

    # --------------------------------------------------------------
    # Validate recommended option
    # --------------------------------------------------------------

    if not isinstance(
        report["recommended_option"],
        str
    ):
        raise ValueError(
            "recommended_option must be a string."
        )

    if not report["recommended_option"].strip():

        raise ValueError(
            "recommended_option cannot be empty."
        )

    # --------------------------------------------------------------
    # Validate Recovery Plan
    # --------------------------------------------------------------

    recovery_plan = report[
        "recovery_plan"
    ]

    if not isinstance(
        recovery_plan,
        dict
    ):
        raise ValueError(
            "recovery_plan must be an object."
        )

    for field in [
        "expected_recovery",
        "actions",
        "remaining_risk"
    ]:

        if field not in recovery_plan:

            raise ValueError(
                f"recovery_plan is missing field: {field}"
            )

    # --------------------------------------------------------------
    # Validate recovery numbers
    # --------------------------------------------------------------

    try:

        value_at_risk = float(
            problem["value_at_risk"]
        )

        expected_recovery = float(
            recovery_plan["expected_recovery"]
        )

        remaining_risk = float(
            recovery_plan["remaining_risk"]
        )

    except (
        TypeError,
        ValueError
    ) as e:

        raise ValueError(
            "Recovery financial values must be numbers."
        ) from e

    if expected_recovery < 0:

        raise ValueError(
            "expected_recovery cannot be negative."
        )

    if expected_recovery > value_at_risk:

        raise ValueError(
            "expected_recovery cannot exceed value_at_risk."
        )

    expected_remaining_risk = round(
        value_at_risk - expected_recovery,
        2
    )

    if round(
        remaining_risk,
        2
    ) != expected_remaining_risk:

        raise ValueError(
            "remaining_risk does not equal "
            "value_at_risk - expected_recovery."
        )

    # --------------------------------------------------------------
    # Validate recovery actions
    # --------------------------------------------------------------

    actions = recovery_plan[
        "actions"
    ]

    if not isinstance(
        actions,
        list
    ):
        raise ValueError(
            "recovery_plan.actions must be a list."
        )

    try:

        units_at_risk = int(
            problem["units_at_risk"]
        )

    except (
        TypeError,
        ValueError
    ) as e:

        raise ValueError(
            "units_at_risk must be an integer."
        ) from e

    total_action_units = 0

    for action in actions:

        if not isinstance(
            action,
            dict
        ):
            raise ValueError(
                "Each recovery action must be an object."
            )

        if "units" not in action:

            raise ValueError(
                "Recovery action is missing 'units'."
            )

        if "action" not in action:

            raise ValueError(
                "Recovery action is missing 'action'."
            )

        try:

            action_units = int(
                action["units"]
            )

        except (
            TypeError,
            ValueError
        ) as e:

            raise ValueError(
                "Recovery action units must be numbers."
            ) from e

        if action_units <= 0:

            raise ValueError(
                "Recovery action units must be greater than zero."
            )

        if not isinstance(
            action["action"],
            str
        ):

            raise ValueError(
                "Recovery action description must be a string."
            )

        total_action_units += action_units

    if total_action_units > units_at_risk:

        raise ValueError(
            "Total recovery action units exceed units_at_risk."
        )

    return True


# --------------------------------------------------------------------------
# Full Pipeline
# --------------------------------------------------------------------------

def run_pipeline(problem_id_or_dict, product_dict: dict = None) -> dict:
    """
    Single public entry point for the backend.

    Accepts either:
      - problem_id: int (loads Problem & Product from SQLite DB)
      - problem_dict: dict, product_dict: dict (runs directly from dictionaries)

    Runs:
        Problem
          ↓
        Sales Agent
          ↓
        Inventory Agent
          ↓
        Finance Agent
          ↓
        Web Research Agent
          ↓
        Strategy Agent
          ↓
        Final JSON validation
          ↓
        Return final report
    """

    db = SessionLocal()
    problem = None

    try:
        if isinstance(problem_id_or_dict, int):
            problem_id = problem_id_or_dict
            # --------------------------------------------------------------
            # Load Problem from DB
            # --------------------------------------------------------------
            problem = (
                db.query(Problem)
                .filter(
                    Problem.id == problem_id
                )
                .first()
            )

            if problem is None:
                raise ValueError(
                    f"No problem found with id={problem_id}"
                )

            product = (
                db.query(Product)
                .filter(
                    Product.id == problem.product_id
                )
                .first()
            )

            problem_data = {
                "product": (
                    product.name
                    if product
                    else "Unknown product"
                ),
                "units_at_risk": problem.units_at_risk,
                "value_at_risk": problem.value_at_risk,
                "root_cause": problem.root_cause
            }
        elif isinstance(problem_id_or_dict, dict):
            p_dict = problem_id_or_dict
            prod = product_dict or {}
            prod_name = prod.get("name") or p_dict.get("product", "Unknown product")
            problem_data = {
                "product": prod_name,
                "units_at_risk": int(p_dict.get("units_at_risk", 0)),
                "value_at_risk": float(p_dict.get("value_at_risk", 0.0)),
                "root_cause": p_dict.get("root_cause", "")
            }
        else:
            raise ValueError(f"Invalid argument to run_pipeline: {type(problem_id_or_dict)}")


        # --------------------------------------------------------------
        # 1. Sales Agent
        # --------------------------------------------------------------

        sales_result = sales_agent(
            problem_data
        )

        # --------------------------------------------------------------
        # 2. Inventory Agent
        # --------------------------------------------------------------

        inventory_result = inventory_agent(
            problem_data
        )

        # --------------------------------------------------------------
        # 3. Finance Agent
        # --------------------------------------------------------------

        finance_result = finance_agent(
            problem_data,
            sales_result,
            inventory_result
        )

        # --------------------------------------------------------------
        # 4. Web Research Agent
        # --------------------------------------------------------------

        try:

            external_options = search_external_options(
                product_name=problem_data["product"],
                root_cause=problem_data["root_cause"]
            )

        except Exception as e:

            print(
                f"[Web Research Agent] Search failed. "
                f"Using fallback: {e}"
            )

            external_options = []

        # --------------------------------------------------------------
        # 5. Strategy Agent
        # --------------------------------------------------------------

        strategy_result = strategy_agent(
            problem_data,
            sales_result,
            inventory_result,
            finance_result,
            external_options
        )

        # --------------------------------------------------------------
        # Final Report
        # --------------------------------------------------------------

        final_report = {
            "problem": problem_data,

            "sales_assessment": sales_result,

            "inventory_assessment": inventory_result,

            "finance_assessment": finance_result,

            "external_options": external_options,

            "recommended_option": strategy_result.get(
                "recommended_option",
                "Manual review needed"
            ),

            "recovery_plan": strategy_result.get(
                "recovery_plan",
                {
                    "expected_recovery": 0,
                    "actions": [],
                    "remaining_risk": (
                        problem_data["value_at_risk"]
                    )
                }
            )
        }

        # --------------------------------------------------------------
        # FINAL CONTRACT VALIDATION
        # --------------------------------------------------------------

        _validate_final_report(
            final_report
        )

        # --------------------------------------------------------------
        # Mark problem as analyzed if DB model is present
        # --------------------------------------------------------------

        if problem is not None:
            problem.status = "analyzed"
            db.commit()

        return final_report

    except Exception as e:

        db.rollback()

        # Preserve useful validation/problem messages.
        if isinstance(
            e,
            ValueError
        ) and str(e).startswith(
            "No problem found"
        ):

            raise

        if isinstance(
            e,
            ValueError
        ) and (
            "Final report" in str(e)
            or "recovery_plan" in str(e)
            or "external_options" in str(e)
            or "recommended_option" in str(e)
            or "assessment" in str(e)
        ):

            raise RuntimeError(
                f"Final JSON validation failed: {e}"
            ) from e

        raise RuntimeError(
            f"Business Rescue pipeline failed: {e}"
        ) from e


    finally:

        db.close()


# --------------------------------------------------------------------------
# Manual Test
# --------------------------------------------------------------------------

if __name__ == "__main__":

    from database.seed_data import seed

    seed()

    db = SessionLocal()

    try:

        first_problem = (
            db.query(Problem)
            .first()
        )

    finally:

        db.close()

    if first_problem is None:

        print(
            "No problems in the database. "
            "Run database/seed_data.py first."
        )

    else:

        try:

            result = run_pipeline(
                first_problem.id
            )

            print(
                json.dumps(
                    result,
                    indent=2,
                    ensure_ascii=False
                )
            )

        except Exception as e:

            print(
                f"[Pipeline Error] {e}"
            )
